#Makefile
run-dist:
	./build/install/app/bin/app
clean:
	./gradlew clean
installDist:
	./gradlew installDist
run:
	./gradlew run
check:
	./gradlew check
run-dist1:
	./build/install/app/bin/app -h
run-dist2:
	./build/install/app/bin/app -h -f=upper ./f1 ./f2
run-dist3:
	./build/install/app/bin/app -f=upper ./f1 ./f2