name: test project
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Run test project"
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.11" # Quotes required to prevent YAML converting to number
      - name: Build with Gradle
        run: ./app/gradlew build
        working-directory: ./app

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/app/build/test-results/test/TEST-*.xml'
