name: test project
on: push
jobs: 
 build: 
  runs-on: ubuntu-latest
  steps:
   - run: echo "🎉 Run test project"
   - uses: actions/checkout@v4
   - name: Set up JDK
     uses: actions/setup-java@v4
     with:
       java-version: '21'
       distribution: 'temurin'
       architecture: x64
   - name: Setup Gradle 8.10
     uses: gradle/actions/setup-gradle@v4
     with:
      gradle-version: "8.12"
   - name: Build with Gradle
     run: gradle/actions build
   - name: Upload build artifacts
     uses: actions/upload-artifact@v4
     with:
      name: Package
      path: hexlet/code
