name: test project
on: push
jobs: 
 build: 
  runs-on: ubuntu-latest

  steps:
   - run: echo "🎉 Run test project"
   - uses: actions/checkout@v4
   - uses: actions/setup-java@v4
     with:
       java-version: '21'
       distribution: 'temurin'
   - uses: gradle/actions/setup-gradle@v4
     with:
         gradle-version: 8.11
   - run: ./gradlew check
   - run: ./gradlew test
